### ISSUE TITLE
No data showing in card

### ISSUE THREAD

**Issue by KoenGullentops** [bollewolle/delijn-card#1]
hi,

Thanks for the good work. I've the DeLijn sensor working properly but can't get the card to work. Nothing is shown. Could you please help me out?

The sensor is returning;

`{
  "attribution": "Data provided by data.delijn.be",
  "stopname": "Kroonstraat, Beerzel",
  "line_number_public": "510",
  "line_transport_type": "BUS",
  "final_destination": "Mechelen Station",
  "due_at_schedule": "2019-08-09T07:09:00+00:00",
  "due_at_realtime": null,
  "next_passages": [
    {
      "passage": 0,
      "stopname": "Kroonstraat, Beerzel",
      "line_number": 510,
      "direction": "HEEN",
      "final_destination": "Mechelen Station",
      "due_at_schedule": "2019-08-09T07:09:00+00:00",
      "due_at_realtime": null,
      "due_in_min": 22,
      "line_number_public": "510",
      "line_desc": "Mechelen - Heist-op-den-Berg - Westerlo - Geel",
      "line_transport_type": "BUS",
      "line_number_colourFront": "WI",
      "line_number_colourFrontHex": "FFFFFF",
      "line_number_colourBack": "DB",
      "line_number_colourBackHex": "0044BB",
      "line_number_colourFrontBorder": "ZW",
      "line_number_colourFrontBorderHex": "000000",
      "line_number_colourBackBorder": "DB",
      "line_number_colourBackBorderHex": "0044BB"
    },
    {
      "passage": 1,
      "stopname": "Kroonstraat, Beerzel",
      "line_number": 511,
      "direction": "HEEN",
      "final_destination": "Mechelen Station",
      "due_at_schedule": "2019-08-09T07:36:00+00:00",
      "due_at_realtime": "2019-08-09T07:36:00+00:00",
      "due_in_min": 49,
      "line_number_public": "511",
      "line_desc": "Mechelen - Heist-op-den-Berg - Herentals",
      "line_transport_type": "BUS",
      "line_number_colourFront": "ZW",
      "line_number_colourFrontHex": "000000",
      "line_number_colourBack": "MU",
      "line_number_colourBackHex": "77CCAA",
      "line_number_colourFrontBorder": "WI",
      "line_number_colourFrontBorderHex": "FFFFFF",
      "line_number_colourBackBorder": "MU",
      "line_number_colourBackBorderHex": "77CCAA"
    },
    {
      "passage": 2,
      "stopname": "Kroonstraat, Beerzel",
      "line_number": 510,
      "direction": "HEEN",
      "final_destination": "Mechelen Station",
      "due_at_schedule": "2019-08-09T08:09:00+00:00",
      "due_at_realtime": "2019-08-09T08:09:00+00:00",
      "due_in_min": 82,
      "line_number_public": "510",
      "line_desc": "Mechelen - Heist-op-den-Berg - Westerlo - Geel",
      "line_transport_type": "BUS",
      "line_number_colourFront": "WI",
      "line_number_colourFrontHex": "FFFFFF",
      "line_number_colourBack": "DB",
      "line_number_colourBackHex": "0044BB",
      "line_number_colourFrontBorder": "ZW",
      "line_number_colourFrontBorderHex": "000000",
      "line_number_colourBackBorder": "DB",
      "line_number_colourBackBorderHex": "0044BB"
    },
    {
      "passage": 3,
      "stopname": "Kroonstraat, Beerzel",
      "line_number": 511,
      "direction": "HEEN",
      "final_destination": "Mechelen Station",
      "due_at_schedule": "2019-08-09T08:36:00+00:00",
      "due_at_realtime": null,
      "due_in_min": 109,
      "line_number_public": "511",
      "line_desc": "Mechelen - Heist-op-den-Berg - Herentals",
      "line_transport_type": "BUS",
      "line_number_colourFront": "ZW",
      "line_number_colourFrontHex": "000000",
      "line_number_colourBack": "MU",
      "line_number_colourBackHex": "77CCAA",
      "line_number_colourFrontBorder": "WI",
      "line_number_colourFrontBorderHex": "FFFFFF",
      "line_number_colourBackBorder": "MU",
      "line_number_colourBackBorderHex": "77CCAA"
    },
    {
      "passage": 4,
      "stopname": "Kroonstraat, Beerzel",
      "line_number": 510,
      "direction": "HEEN",
      "final_destination": "Mechelen Station",
      "due_at_schedule": "2019-08-09T09:09:00+00:00",
      "due_at_realtime": null,
      "due_in_min": 142,
      "line_number_public": "510",
      "line_desc": "Mechelen - Heist-op-den-Berg - Westerlo - Geel",
      "line_transport_type": "BUS",
      "line_number_colourFront": "WI",
      "line_number_colourFrontHex": "FFFFFF",
      "line_number_colourBack": "DB",
      "line_number_colourBackHex": "0044BB",
      "line_number_colourFrontBorder": "ZW",
      "line_number_colourFrontBorderHex": "000000",
      "line_number_colourBackBorder": "DB",
      "line_number_colourBackBorderHex": "0044BB"
    }
  ],
  "friendly_name": "Kroonstraat, Beerzel",
  "icon": "mdi:bus",
  "device_class": "timestamp"
}`

**Comment by KoenGullentops** [comment]
I'll add the lovelace card config as reference:

`- type: custom:delijn-card
        entity: sensor.kroonstraat_beerzel
        title: 'De Lijn'
        config_type: columns
        columns:
          - field: line_number_public
            title: Bus
          - field: line_transport_type
            title: Type
          - field: final_destination
            title: Naar
          - field: due_in_min
            title: Komt binnen (min)
          - field: due_at_sch
            title: Aankomst (gepland)`

**Comment by KoenGullentops** [comment]
hi,
The card works with the default settings but as soon as I add fields: due_at_rt and/or due_at_sch the list is empty.

thx
Koen

**Comment by KoenGullentops** [comment]
Hi, I found the issue. The field names are different in the response message from De Lijn.

**Comment by geertmeersman** [comment]
Correct ;-)
```
      - type: 'custom:delijn-card'
        entity: sensor.xxxxxxx
        title: 'xxxxxx'
        config_type: columns
        columns:
          - field: line_number_public
            title: Lijn
          - field: line_transport_type
            title: Type
          - field: final_destination
            title: Eindbestemming
          - field: due_in_min
            title: Passeert binnen (min)
          - field: due_at_realtime
            title: Vertrek (real-time)
          - field: due_at_schedule
            title: Vertrek (gepland)
```

Took me a little to figure it out too!
Anyway, thx a lot for this card @bollewolle !

**Comment by bollewolle** [comment]
Sorry, for some reason I didn't receive a notification for this issue :s Anyway, I indeed had to change some of the variable names at request of the HA devs to make the more clear. Might not have updated the documentation of the card yet, I'll try to do that as soon as possible. Sorry for the inconvenience.

**Comment by geertmeersman** [comment]
No worries Bram, quite happy you share your code!

**Comment by waldhari81** [comment]
I still have the problem though
second one is the default, that works
![Screenshot_20200315_105917](https://user-images.githubusercontent.com/48049836/76699262-39e5f000-66ac-11ea-99be-efd8a5922254.jpeg)
This is what I did on the custom
![Screenshot_20200315_110145](https://user-images.githubusercontent.com/48049836/76699288-79144100-66ac-11ea-8e2d-571d85e1bc12.jpeg)

**Comment by waldhari81** [comment]
I tried a multiple busstops and then it did show one on the manual card. But I find it strange that the default integration does show the correct information.

**Comment by bollewolle** [comment]
The documentation has been updated so I guess this can be closed now.
