### ISSUE TITLE
If the bus line has no next passages anymore, crash of card

### ISSUE THREAD

**Issue by ericvb** [bollewolle/delijn-card#2]
Hi,

The code didn't work for me, so I did some debug.

If feed is undefined, this line 78 will give an error
`const rowLimit = config.row_limit ? config.row_limit : Object.keys(feed).length;`
Feed gets his value from (line 74):
`const feed = hass.states[config.entity].attributes['next_passages'];`
But in case there are no 'next_passages' anymore, feed will be undefined!

Is config.row_limit a undocumented configuration option? It is not mentioned in the Readme.md?

I've changed my local code to use a constant number of 10 when feed is undefined:
`const rowLimit = config.row_limit ? config.row_limit : feed ? Object.keys(feed).length : 10;`

Further on I changed also the display code to display a message 'No passages anymore today' in case the feed is undefined or that the length is 0 of Object.keys(feed).
Replaced the code :
`
        } else {
          this.style.display = 'none';
        }`
by
`
        } else {
          root.getElementById('container').innerHTML = '<div><span>No passages anymore today</span></div>'
          //this.style.display = 'none';
        }`

On line 95 there is also a typo:
` let card_content = '<table><thread><tr>';`
Should be:
` let card_content = '<table><thead><tr>';`
Normally this is not a problem as browsers are forgiving for erroneous tags

**Comment by bollewolle** [comment]
Hi @ericvb ,

Many thanks for the proposed fixes. I'm afraid that JavaScript and html aren't my strong suit, so that's why I based myself upon previously created Lovelace cards. That might explain why there's still a config.row_limit in there as well. I left it as is currently is but implemented all the changes you proposed. 

Should be fine now, do let me know if it isn't. Or feel free to do a PR yourself of course :)

Cheers,
Bram

**Comment by ericvb** [comment]
Hi Bram,
Thanks for the modifications :-)

I did a last modification : I replaced the English text 'no passages anymore today' by icons
`root.getElementById('container').innerHTML = '<table><tbody><tr><td><ha-icon icon="mdi:bus-multiple"></ha-icon><ha-icon icon="mdi:do-not-disturb"></ha-icon></td></tr></tbody></table>';`

I first searched in the homeassistant documentation if localization was possible, but didn't find for custom lovelace cards, so I switched to use icons, a universal language...

Regards,
