### ISSUE TITLE
De Lijn stopped working

### ISSUE THREAD

**Issue by Meerkater** [bollewolle/delijn-card#4]
I'm using delijn-card for more than a week and everything worked fine. After the lastest Home Assistant update it stopped working and always shows 'No passages anymore today'.

**Comment by bollewolle** [comment]
Is this still an issue or has it been resolved by now? Could you provide me de stop_id that you are using for De Lijn so I can look into it? Because my 3 stop_id's seem to be working, so I'd need to know the one you're using so I can find out what the issue is.
Thanks!

**Comment by Meerkater** [comment]
This is already resolved.

Op ma 27 apr. 2020 15:44 schreef Bram Goolaerts <notifications@github.com>:

**Comment by bollewolle** [comment]
Alright, will close the issue then.

Thanks.
